name: Publish to OpenVSX

on:
  push:
    branches: ["past_openvsx"]

jobs:
  publish-openvsx:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - run: npm install
      - run: npm install -g vsce
      - run: npm run vscode:prepublish
      
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_PAT }}
          registryUrl: https://open-vsx.org
          
      - name: End of workflow
        run: echo "Finished publishing to OpenVSX"
